### ISSUE TITLE
Missing minified file

### ISSUE THREAD

**Issue by ivanquirino** [jrburke/requirejs-bower#5]
The bower packaging should include the minified file too.

**Comment by JoniJnm** [comment]
Alternative:

https://github.com/JoniJnm/requirejs-bower

**Comment by fourpixels** [comment]
You are saying that require is used with r.js, but this is **not the only truth**, as sometimes people simply don't need to optimize them, or already have them optimized. This is a bower package, so people usually just **import** files from it.

By sayin/doing so, you are simply linking two separate things and making one not work without the other! We have to use some other tool to minify this piece of code.
I don't see what's the problem providing the minified version, as so many people really say they need it. It doesn't matter how they can minify it by themselves, it's a matter of how easy to use the module is. And I don't see any strong arguments **against** that..

**Comment by JoniJnm** [comment]
I need the minimized version because I need a dynamic config. I include:

* require.min.js (lib)
* config.js (common requirejs config)
* dynamic inline script that overwrites some requirejs config and depends on the enviroment
* main.js (generated by r.js)
