### ISSUE TITLE
Serve minified version

### ISSUE THREAD

**Issue by AlicanC** [jrburke/requirejs-bower#7]
Most Bower packages come with a minified version of libraries and a sourcemap for debugging purposes.

We could minify it in our own build processes, but minifiers can break libraries so they are better minified and tested by their authors.

**Comment by AlicanC** [comment]
I should also note that older requests for this (#3 #5 #6) do not mention the possible breakage. This is a problem with Jade and it pushes users of these libraries to look for officially minified and tested files:
https://github.com/jadejs/jade/issues/298

Also one of the reasons given why this won't happen is that the best practice is to use "r.js". The minified version being available for download on the [webpage](http://requirejs.org/docs/download.html) conflicts with this reasoning.

**Comment by jrburke** [comment]
I just do not believe this is the right way forward for delivering packages of code with both a non-minified and minified version in the package. I do not see this as how JS code in general will be delivered in the future once modules become more widespread for the front end. If this is needed, then someone else who really wants it can create a separate repo for those purposes.

**Comment by AlicanC** [comment]
Can you at least update the documentation with information on how to minify it? A link to the script you use to generate the minified version on the webpage would suffice. Then at least we can have the confidence of using the same minifier and options that you use with it. Even if minification of the library doesn't require anything special, it would be nice to know that it doesn't.

**Comment by cdll** [comment]
oh i got it~
